import { Box, Heading } from "@chakra-ui/react";
import Head from "next/head";
import { Hero } from "../components";
export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </Box>
  );
}
